image: node:slim

# GitLab pages
# https://gitlab.com/help/user/project/pages/getting_started_part_two.md
pages:
  script:
    - yarn
    - yarn run build
    - mv _book public
  artifacts:
    paths:
      - public
